[project]
name = "icn"
version = "0.1.1"
description = "Fork of icn-tools with updated dependencies and package-i-fied metadata"
readme = "README.md"
requires-python = ">=3.06"
dependencies = [
    "numpy",
    "pandas",
    "contourpy",
    "scikit-image",
    "scikit-learn",
    "statsmodels",
    "six",
    "requests",
    "mne",
    "mne_bids",
    "psutil",
]


[tool.setuptools.packages.find]
where = ["src"]
include = ["icn*"]
