[project]
name = "icn"
version = "0.1.0"
description = "Fork of icn-tools with updated dependencies and package-i-fied metadata"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas <1.5",
    "numpy <2.1",
    "contourpy <1.3.3",
    "scikit-image",
    "scikit-learn",
    "statsmodels",
    "six",
    "requests",
    "mne",
    "mne_bids",
]


[tool.setuptools.packages.find]
where = ["src"]
include = ["icn*"]
